//! Generate checked-in references from the executable's CLI definition.
#[path = "../src/cli.rs"]
mod cli;
#[path = "../src/prefix.rs"]
#[allow(dead_code)]
mod prefix;

use anyhow::{Context, Result, bail};
use clap::CommandFactory;
use std::path::Path;

fn main() -> Result<()> {
    let args: Vec<_> = std::env::args().skip(1).collect();
    let check = match args.as_slice() {
        [] => false,
        [flag] if flag == "--check" => true,
        _ => bail!("Usage: cargo run --example generate_docs -- [--check]"),
    };
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut command = cli::Args::command();
    // Keep generated references independent of the machine and checkout.
    command = command
        .long_version(env!("CARGO_PKG_VERSION"))
        .term_width(88)
        .disable_colored_help(true);
    let help = command.render_long_help().to_string();
    let help = help
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    let markdown = format!(
        "<!-- Generated by make docs-generate; edit src/cli.rs instead. -->\n\n# Command-line reference\n\n```text\n{help}```\n\nSee the [configuration reference](configuration.md), [interactive controls](../guide/controls.md), and [manpage](manpage.md).\n"
    );
    let mut man = Vec::new();
    let manual = clap_mangen::Man::new(command)
        .section("1")
        .title("NYSOS")
        .date("2026-09-21")
        .manual("User Commands");
    manual.render_title(&mut man)?;
    manual.render_name_section(&mut man)?;
    // clap_mangen 0.2 omits option value placeholders in its synopsis.
    // Use the same compact synopsis as --help; OPTIONS documents each value.
    man.extend_from_slice(b".SH SYNOPSIS\n.B nysos\n.RI [ OPTIONS ]\n");
    manual.render_description_section(&mut man)?;
    manual.render_options_section(&mut man)?;
    man.extend_from_slice(include_bytes!("../docs/man/extra.roff"));
    manual.render_version_section(&mut man)?;
    // Roff fills ordinary text lines. Wrap source prose for readable diffs and
    // mandoc lint, leaving macros and their arguments untouched.
    let mut formatted = String::new();
    for line in std::str::from_utf8(&man)?.lines() {
        if line.starts_with('.') || line.starts_with('\'') {
            formatted.push_str(line.trim_end());
        } else {
            let mut width = 0;
            for word in line.split_whitespace() {
                if width != 0 {
                    if width + 1 + word.len() > 78 {
                        formatted.push('\n');
                        width = 0;
                    } else {
                        formatted.push(' ');
                        width += 1;
                    }
                }
                // A leading dot/apostrophe must remain text rather than a macro.
                if width == 0 && word.starts_with(['.', '\'']) {
                    formatted.push_str("\\&");
                }
                formatted.push_str(word);
                width += word.len();
            }
        }
        formatted.push('\n');
    }
    let formatted = formatted.replace(".br\n\n.br\n", ".sp\n");
    for (relative, contents) in [
        ("docs/reference/cli.md", markdown.as_bytes()),
        ("docs/man/nysos.1", formatted.as_bytes()),
    ] {
        let path = root.join(relative);
        if check {
            let existing = std::fs::read(&path)
                .with_context(|| format!("Reading {relative}; run make docs-generate"))?;
            if existing != contents {
                bail!("{relative} is stale; run make docs-generate");
            }
            println!("Current: {relative}");
        } else {
            std::fs::write(&path, contents)?;
            println!("Generated {relative}");
        }
    }
    Ok(())
}
